// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTruyenTranh.Models;

#nullable disable

namespace WebTruyenTranh.Migrations
{
    [DbContext(typeof(TruyenSongNguContext))]
    [Migration("20260729163042_SyncMissingColumns")]
    partial class SyncMissingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTruyenTranh.Models.TblAdmin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdminId")
                        .HasName("PK__tblAdmin__719FE4E843CF3D0E");

                    b.HasIndex(new[] { "Username" }, "UQ__tblAdmin__536C85E44AFAD200")
                        .IsUnique();

                    b.ToTable("tblAdmin", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("tblAuthor", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("tblCategory", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblCategoryOfStory", b =>
                {
                    b.Property<int>("CategoryOfStoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryOfStoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryOfStoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    b.HasKey("CategoryOfStoryId")
                        .HasName("PK__tblCateg__7A175BD169EAD37F");

                    b.HasIndex("StoryId");

                    b.HasIndex(new[] { "CategoryId", "StoryId" }, "UQ__tblCateg__8AE116288418053F")
                        .IsUnique();

                    b.ToTable("tblCategoryOfStory", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblChapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChapterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ChapterId")
                        .HasName("PK__tblChapt__0893A34A0530B0E7");

                    b.HasIndex("StoryId");

                    b.ToTable("tblChapter", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblChapterComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int")
                        .HasColumnName("ChapterID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CommentId")
                        .HasName("PK__tblChapt__C3B4DFAA3AD24B83");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId");

                    b.ToTable("tblChapterComment", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Count_Likes");

                    b.Property<DateTime?>("CreateAd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreateAD")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CommentId")
                        .HasName("PK__tblComme__C3B4DFAAEFD2F427");

                    b.HasIndex("StoryId");

                    b.ToTable("tblComment", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblParagraph", b =>
                {
                    b.Property<int>("ParagraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParagraphID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParagraphId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int")
                        .HasColumnName("ChapID");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<int>("ParagraphOrder")
                        .HasColumnType("int");

                    b.Property<string>("Vietnamese")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("ParagraphId");

                    b.HasIndex("ChapterId");

                    b.ToTable("tblParagraph", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblStory", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<int?>("CountFolower")
                        .HasColumnType("int")
                        .HasColumnName("Count_folower");

                    b.Property<int?>("CountRate")
                        .HasColumnType("int")
                        .HasColumnName("Count_rate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StoryId");

                    b.HasIndex("AuthorId");

                    b.ToTable("tblStory", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreateAd")
                        .HasColumnType("datetime")
                        .HasColumnName("CreateAD");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Img")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Passwork")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reset_token");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("token_expiry");

                    b.HasKey("UserId");

                    b.ToTable("tblUser", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserFollowStory", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FollowID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowId"));

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FollowId")
                        .HasName("PK__tblUserF__2CE8108EC154A014");

                    b.HasIndex("StoryId");

                    b.HasIndex(new[] { "UserId", "StoryId" }, "UQ__tblUserF__8460E0AF2913C658")
                        .IsUnique();

                    b.ToTable("tblUserFollowStory", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserLiking", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    b.Property<DateTime?>("LikedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Liking")
                        .HasColumnType("int");

                    b.HasKey("UserId", "StoryId")
                        .HasName("PK__tblUserL__8460E0AEB4C9A112");

                    b.HasIndex("StoryId");

                    b.ToTable("tblUserLiking", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserRating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryID");

                    b.Property<DateTime?>("RatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("UserId", "StoryId")
                        .HasName("PK__tblUserR__8460E0AE38A9983A");

                    b.HasIndex("StoryId");

                    b.ToTable("tblUserRating", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserReadingProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("LastChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "StoryId")
                        .HasName("PK__tblUserR__8460E04844C6A252");

                    b.ToTable("tblUserReadingProgress", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblVocabulary", b =>
                {
                    b.Property<int>("VocabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VocabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VocabId"));

                    b.Property<string>("ExampleEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExampleEN");

                    b.Property<string>("ExampleVi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExampleVI");

                    b.Property<string>("Meaning")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VocabId")
                        .HasName("PK__tblVocab__BF7A5E590330BD3D");

                    b.ToTable("tblVocabulary", (string)null);
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblCategoryOfStory", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblCategory", "Category")
                        .WithMany("TblCategoryOfStories")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_tblCategoryOfStory_tblCategory");

                    b.HasOne("WebTruyenTranh.Models.TblStory", "Story")
                        .WithMany("TblCategoryOfStories")
                        .HasForeignKey("StoryId")
                        .IsRequired()
                        .HasConstraintName("FK_tblCategoryOfStory_tblStory");

                    b.Navigation("Category");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblChapter", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblStory", "Story")
                        .WithMany("TblChapters")
                        .HasForeignKey("StoryId")
                        .IsRequired()
                        .HasConstraintName("FK__tblChapte__Story__4CA06362");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblChapterComment", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblChapter", "Chapter")
                        .WithMany("TblChapterComments")
                        .HasForeignKey("ChapterId")
                        .IsRequired()
                        .HasConstraintName("FK__tblChapte__Chapt__30C33EC3");

                    b.HasOne("WebTruyenTranh.Models.TblUser", "User")
                        .WithMany("TblChapterComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__tblChapte__UserI__2FCF1A8A");

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblComment", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblStory", "Story")
                        .WithMany("TblComments")
                        .HasForeignKey("StoryId")
                        .IsRequired()
                        .HasConstraintName("FK__tblCommen__Story__71D1E811");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblParagraph", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblChapter", "Chap")
                        .WithMany("TblParagraphs")
                        .HasForeignKey("ChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_tblParagraph_tblChapter");

                    b.Navigation("Chap");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblStory", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblAuthor", "Author")
                        .WithMany("TblStories")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK_tblStory_tblAuthor");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserFollowStory", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblStory", "Story")
                        .WithMany("TblUserFollowStories")
                        .HasForeignKey("StoryId")
                        .IsRequired()
                        .HasConstraintName("FK_tblUserFollowStory_tblStory");

                    b.HasOne("WebTruyenTranh.Models.TblUser", "User")
                        .WithMany("TblUserFollowStories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_tblUserFollowStory_tblUser");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserLiking", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblStory", "Story")
                        .WithMany("TblUserLikings")
                        .HasForeignKey("StoryId")
                        .IsRequired()
                        .HasConstraintName("FK__tblUserLi__Story__208CD6FA");

                    b.HasOne("WebTruyenTranh.Models.TblUser", "User")
                        .WithMany("TblUserLikings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__tblUserLi__UserI__1F98B2C1");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUserRating", b =>
                {
                    b.HasOne("WebTruyenTranh.Models.TblStory", "Story")
                        .WithMany("TblUserRatings")
                        .HasForeignKey("StoryId")
                        .IsRequired()
                        .HasConstraintName("FK__tblUserRa__Story__1BC821DD");

                    b.HasOne("WebTruyenTranh.Models.TblUser", "User")
                        .WithMany("TblUserRatings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__tblUserRa__UserI__1AD3FDA4");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblAuthor", b =>
                {
                    b.Navigation("TblStories");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblCategory", b =>
                {
                    b.Navigation("TblCategoryOfStories");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblChapter", b =>
                {
                    b.Navigation("TblChapterComments");

                    b.Navigation("TblParagraphs");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblStory", b =>
                {
                    b.Navigation("TblCategoryOfStories");

                    b.Navigation("TblChapters");

                    b.Navigation("TblComments");

                    b.Navigation("TblUserFollowStories");

                    b.Navigation("TblUserLikings");

                    b.Navigation("TblUserRatings");
                });

            modelBuilder.Entity("WebTruyenTranh.Models.TblUser", b =>
                {
                    b.Navigation("TblChapterComments");

                    b.Navigation("TblUserFollowStories");

                    b.Navigation("TblUserLikings");

                    b.Navigation("TblUserRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
